### PR TITLE
README update

### PR DESCRIPTION
**Pull request by oliver-walker-hms**

### CODE REVIEW

**Review by alexjhawk — APPROVED** [review]

**Review by TomKimsey — COMMENTED** [review]
Is more information needed to find out what the full url is? How do you find that you should include /Thingworx/Things/ConnectorHost/Services/TakeInfo, how would you know if your url is different?

**Comment by oliver-walker-hms** [comment]
@alexjhawk , do you have more information on this? I was under the impression /Thingworx/Things/ConnectorHost/Services/TakeInfo would be the default of a configurable endpoint.

**Comment by alexjhawk** [comment]
> @alexjhawk , do you have more information on this? I was under the impression /Thingworx/Things/ConnectorHost/Services/TakeInfo would be the default of a configurable endpoint.

I think this should be left as is for now. In the current state, it only will ever be "/Thingworx/Things/ConnectorHost/Services/TakeInfo". After the changes I'm working on on the Thingworx side are complete, that will change.

**Comment by TomKimsey** [comment]
> > @alexjhawk , do you have more information on this? I was under the impression /Thingworx/Things/ConnectorHost/Services/TakeInfo would be the default of a configurable endpoint.
> 
> I think this should be left as is for now (or updated to reflect that its always the same value). In the current state, it only will ever be "/Thingworx/Things/ConnectorHost/Services/TakeInfo". After the changes I'm working on on the Thingworx side are complete, that will change.

okay, It just might confuse some users how this url is obtained as I dont think I saw how to find it in the documentation.

**Review by TomKimsey — APPROVED** [review]

**Comment by alexjhawk** [comment]
> > > @alexjhawk , do you have more information on this? I was under the impression /Thingworx/Things/ConnectorHost/Services/TakeInfo would be the default of a configurable endpoint.
> > 
> > 
> > I think this should be left as is for now (or updated to reflect that its always the same value). In the current state, it only will ever be "/Thingworx/Things/ConnectorHost/Services/TakeInfo". After the changes I'm working on on the Thingworx side are complete, that will change.
> 
> okay, It just might confuse some users how this url is obtained as I dont think I saw how to find it in the documentation.

These changes are part of a larger upgrade in the next version, and the documentation will be updated to show how to find each device's unique endpoint URL (should you chose that route), or the common endpoint URL on the Thingworx side

**Comment by TomKimsey** [comment]
> > > > @alexjhawk , do you have more information on this? I was under the impression /Thingworx/Things/ConnectorHost/Services/TakeInfo would be the default of a configurable endpoint.
> > > 
> > > 
> > > I think this should be left as is for now (or updated to reflect that its always the same value). In the current state, it only will ever be "/Thingworx/Things/ConnectorHost/Services/TakeInfo". After the changes I'm working on on the Thingworx side are complete, that will change.
> > 
> > 
> > okay, It just might confuse some users how this url is obtained as I dont think I saw how to find it in the documentation.
> 
> These changes are part of a larger upgrade in the next version, and the documentation will be updated to show how to find each device's unique endpoint URL (should you chose that route), or the common endpoint URL on the Thingworx side

okay, sounds like this concern will be answered in a future PR.

**Pull request merged**
